---
- hosts: all
  become: yes
  tasks:
   - name: i want to install apache2
     apt:
      name: apache2
      state: present
      register: myresult
  name: i want to debug
  debug:
   msg: "{{myresult}}"